TRUNCATE TABLE TBL_ITEM_DATA;
TRUNCATE TABLE TBL_PICTURE_DATA;

INSERT INTO TBL_ITEM_DATA(ITEM_ID,ITEM_NAME,ITEM_COST,INCREASE_COOKIE ,PICTURE_ID ,DISPLAY_ORDER) VALUES('ITEM_0000','手袋','100','100','PICTURE_0000','0');
INSERT INTO TBL_ITEM_DATA(ITEM_ID,ITEM_NAME,ITEM_COST,INCREASE_COOKIE ,PICTURE_ID ,DISPLAY_ORDER) VALUES('ITEM_0001','BBA','500','500','PICTURE_0001','1');
INSERT INTO TBL_ITEM_DATA(ITEM_ID,ITEM_NAME,ITEM_COST,INCREASE_COOKIE ,PICTURE_ID ,DISPLAY_ORDER) VALUES('ITEM_0002','農場','1000','1000','PICTURE_0002','2');
INSERT INTO TBL_ITEM_DATA(ITEM_ID,ITEM_NAME,ITEM_COST,INCREASE_COOKIE ,PICTURE_ID ,DISPLAY_ORDER) VALUES('ITEM_0003','鉱山','10000','5000','PICTURE_0003','3');
INSERT INTO TBL_ITEM_DATA(ITEM_ID,ITEM_NAME,ITEM_COST,INCREASE_COOKIE ,PICTURE_ID ,DISPLAY_ORDER) VALUES('ITEM_0004','工場','20000','10000','PICTURE_0004','4');
INSERT INTO TBL_ITEM_DATA(ITEM_ID,ITEM_NAME,ITEM_COST,INCREASE_COOKIE ,PICTURE_ID ,DISPLAY_ORDER) VALUES('ITEM_0005','銀行','50000','20000','PICTURE_0005','5');
INSERT INTO TBL_ITEM_DATA(ITEM_ID,ITEM_NAME,ITEM_COST,INCREASE_COOKIE ,PICTURE_ID ,DISPLAY_ORDER) VALUES('ITEM_0006','魔女の塔','70000','30000','PICTURE_0006','6');
INSERT INTO TBL_ITEM_DATA(ITEM_ID,ITEM_NAME,ITEM_COST,INCREASE_COOKIE ,PICTURE_ID ,DISPLAY_ORDER) VALUES('ITEM_0007','宇宙人','100000','50000','PICTURE_0007','7');


INSERT INTO TBL_PICTURE_DATA (PICTURE_ID ,PICTURE_NAME ,PICTURE_PASS) VALUES('PICTURE_0000','手袋','/image/item1.png');
INSERT INTO TBL_PICTURE_DATA (PICTURE_ID ,PICTURE_NAME ,PICTURE_PASS) VALUES('PICTURE_0001','BBA','/image/item2.png');
INSERT INTO TBL_PICTURE_DATA (PICTURE_ID ,PICTURE_NAME ,PICTURE_PASS) VALUES('PICTURE_0002','農場','/image/item3.png');
INSERT INTO TBL_PICTURE_DATA (PICTURE_ID ,PICTURE_NAME ,PICTURE_PASS) VALUES('PICTURE_0003','鉱山','/image/item4.png');
INSERT INTO TBL_PICTURE_DATA (PICTURE_ID ,PICTURE_NAME ,PICTURE_PASS) VALUES('PICTURE_0004','工場','/image/item5.png');
INSERT INTO TBL_PICTURE_DATA (PICTURE_ID ,PICTURE_NAME ,PICTURE_PASS) VALUES('PICTURE_0005','銀行','/image/item6.png');
INSERT INTO TBL_PICTURE_DATA (PICTURE_ID ,PICTURE_NAME ,PICTURE_PASS) VALUES('PICTURE_0006','魔女の塔','/image/item7.png');
INSERT INTO TBL_PICTURE_DATA (PICTURE_ID ,PICTURE_NAME ,PICTURE_PASS) VALUES('PICTURE_0007','宇宙人','/image/item8.png');